/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: andictl@andi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mobilemoneysdk

type ProviderProvider struct {
	ID       string `json:"ID"`
	Name     string `json:"Name"`
	Platform string `json:"Platform"`
	Token    string `json:"Token"`
	Type_    string `json:"Type"`
}
