/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PaymentCreateOrder struct {
	AppId string `json:"AppId"`
	AppName string `json:"AppName"`
	ExpireDate time.Time `json:"ExpireDate"`
	TotalAmount int64 `json:"TotalAmount"`
}
