/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: andictl@andi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mobilemoneysdk

import (
	"time"
)

type SettingsSettings struct {
	AppWebhook       string    `json:"AppWebhook"`
	ClientId         string    `json:"ClientId"`
	ClientSecret     string    `json:"ClientSecret"`
	Email            string    `json:"Email"`
	Env              string    `json:"Env"`
	Expire           bool      `json:"Expire"`
	ExpireAt         time.Time `json:"ExpireAt"`
	ID               string    `json:"ID"`
	Notification     time.Time `json:"Notification"`
	OwnerId          string    `json:"OwnerId"`
	ProviderCallback string    `json:"ProviderCallback"`
	ProviderId       string    `json:"ProviderId"`
	ProviderPlatform string    `json:"ProviderPlatform"`
	Type_            string    `json:"Type"`
}
