/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PaymentPayment struct {
	BillingProvider string `json:"BillingProvider"`
	Email string `json:"Email"`
	FullName string `json:"FullName"`
	Histories []PaymentPaymentHistory `json:"Histories"`
	ID string `json:"ID"`
	MerchantData string `json:"MerchantData"`
	OrderRefer string `json:"OrderRefer"`
	PayUrl string `json:"PayUrl"`
	ProviderResponse string `json:"ProviderResponse"`
	Status string `json:"Status"`
	TrxID string `json:"TrxID"`
}
