/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SharedTransactionStatus struct {
	Description string `json:"description"`
	Reference string `json:"reference"`
	RequestId string `json:"requestId"`
	Status string `json:"status"`
	TransactionId string `json:"transactionId"`
}
