/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: andictl@andi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mobilemoneysdk

type Partner struct {
	Id     string `json:"id"`
	IdType string `json:"idType"`
}
