/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: andictl@andi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mobilemoneysdk

type MerchantInitPaymentRequest struct {
	Amount              *Amount           `json:"amount"`
	Customer            *SharedIdentifier `json:"customer"`
	Method              string            `json:"method"`
	Partner             *SharedIdentifier `json:"partner"`
	ReceiveNotification bool              `json:"receiveNotification"`
	Reference           string            `json:"reference"`
}
