/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: andictl@andi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mobilemoneysdk

import (
	"time"
)

type SharedTestNumber struct {
	ExpiresAt    time.Time              `json:"expiresAt"`
	Grade        *SharedTestNumberGrade `json:"grade"`
	MerchantCode string                 `json:"merchantCode"`
	Msisdn       string                 `json:"msisdn"`
	PinCode      string                 `json:"pinCode"`
	Type_        string                 `json:"type"`
}
