/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: andictl@andi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mobilemoneysdk

type SharedPublicKey struct {
	Key     string `json:"key"`
	KeyId   string `json:"keyId"`
	KeySize int32  `json:"keySize"`
	KeyType string `json:"keyType"`
}
