/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Partner struct {
	Id string `json:"id"`
	IdType string `json:"idType"`
	WalletType string `json:"walletType"`
}
