/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantPaymentQrcode struct {
	DeepLink string `json:"deepLink"`
	QrCode string `json:"qrCode"`
}
