/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SettingsSettings struct {
	AppWebhook string `json:"AppWebhook"`
	ClientId string `json:"ClientId"`
	ClientSecret string `json:"ClientSecret"`
	Email string `json:"Email"`
	Env string `json:"Env"`
	Expire bool `json:"Expire"`
	ExpireAt time.Time `json:"ExpireAt"`
	ID string `json:"ID"`
	Notification time.Time `json:"Notification"`
	OwnerId string `json:"OwnerId"`
	ProviderCallback string `json:"ProviderCallback"`
	ProviderId string `json:"ProviderId"`
	ProviderPlatform string `json:"ProviderPlatform"`
	ServiceId string `json:"ServiceId"`
	Type_ string `json:"Type"`
}
