/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PaymentPayment struct {
	Amount float64 `json:"Amount"`
	BillingProvider string `json:"BillingProvider"`
	Channel string `json:"Channel"`
	Email string `json:"Email"`
	Env string `json:"Env"`
	FullName string `json:"FullName"`
	Histories []PaymentPaymentHistory `json:"Histories"`
	ID string `json:"ID"`
	MerchantData string `json:"MerchantData"`
	OrderRefer string `json:"OrderRefer"`
	PayUrl string `json:"PayUrl"`
	ProviderRequestDate time.Time `json:"ProviderRequestDate"`
	ProviderResponse string `json:"ProviderResponse"`
	ProviderTrxID string `json:"ProviderTrxID"`
	Status string `json:"Status"`
	TrxID string `json:"TrxID"`
}
