/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: andictl@andi.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mobilemoneysdk

type MerchantOneStepPayment struct {
	Amount    *Amount   `json:"amount"`
	Customer  *Customer `json:"customer"`
	Partner   *Partner  `json:"partner"`
	Reference string    `json:"reference"`
}
