/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PaymentPaymentHistory struct {
	ID string `json:"ID"`
	PaymentRefer string `json:"PaymentRefer"`
	ResponseData string `json:"ResponseData"`
	Status string `json:"Status"`
}
