/*
 * Documentation
 *
 * Resource for api
 *
 * API version: 1.0.0
 * Contact: contact@akouendy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SharedTransaction struct {
	Amount *Amount `json:"amount"`
	Channel string `json:"channel"`
	CreatedAt time.Time `json:"createdAt"`
	Customer *Customer `json:"customer"`
	Metadata *Metadata `json:"metadata"`
	Partner *Partner `json:"partner"`
	ReceiveNotification bool `json:"receiveNotification"`
	Reference string `json:"reference"`
	RequestDate time.Time `json:"requestDate"`
	Status string `json:"status"`
	TransactionId string `json:"transactionId"`
	Type_ string `json:"type"`
	UpdatedAt time.Time `json:"updatedAt"`
}
